# NPTEL R Programming – Week 9: Python / Google Colab Implementation

This notebook translates the Week 9 topics from the NPTEL **Foundations of R Software** notes into Python.

### Covered lectures
- **Lecture 36:** Strings – Display and Formatting (`print`, `cat`)
- **Lecture 37:** Strings – Display and Formatting (`paste`, `paste0`)
- **Lecture 38:** String Splitting (`strsplit`)
- **Lecture 39:** String Manipulations and Alphabets (`nchar`, `nzchar`, `tolower`, `toupper`)

> The goal is to reproduce the concepts and examples from the notes using standard Python.


## 1. Import required libraries

Most examples only require Python's built-in string operations. `numpy` is included for convenient vector-style demonstrations.

In [1]:
import math
import numpy as np

print("Python environment is ready!")


Python environment is ready!


# Lecture 36 – Display and Formatting of Strings

The notes explain that R's `print()` is primarily for printing one object at a time, while `cat()` can concatenate multiple items and print them as continuous output. fileciteturn2file0L21-L36

Python's `print()` can directly print multiple objects, so it combines the roles illustrated by R's `print()` and `cat()`.

In [2]:
# R:
# print("The zero occurs at", 2*pi, "radians.")

# Python equivalent
x = 2 * math.pi
print("The zero occurs at", x, "radians.")


The zero occurs at 6.283185307179586 radians.


## R `cat()` equivalent

R `cat()` places a space between arguments by default and uses `\n` for a newline. fileciteturn2file0L53-L58

In Python, `print()` provides similar behavior.

In [3]:
print("The zero occurs at", 2 * math.pi, "radians.")
print()

# Explicit separator
print("The zero occurs at", 2 * math.pi, "radians.", sep=" ")


The zero occurs at 6.283185307179586 radians.

The zero occurs at 6.283185307179586 radians.


## Date display example

In [4]:
from datetime import datetime

today = datetime.now()
print("Today's date is:", today)


Today's date is: 2026-10-01 08:48:02.865617


## Separator examples

The notes demonstrate `cat(x, sep=" ++ ")` and `cat(x, sep=" / ")`. fileciteturn2file0L103-L111

Python's `str.join()` is a close equivalent for joining vector elements with a separator.

In [5]:
x = list(range(1, 11))

print(" ++ ".join(map(str, x)))
print(" / ".join(map(str, x)))


1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10


## Formatting numeric values

In [6]:
x = 7

print("The square of", x, "is", x**2, "!")
print(f"The square of {x} is {x**2} !")

# R format(sqrt(x), digits=3) is approximated with Python numeric formatting.
print(f"The square root of {x} is approximately {math.sqrt(x):.3g}")


The square of 7 is 49 !
The square of 7 is 49 !
The square root of 7 is approximately 2.65


## Printing a vector of even numbers

In [7]:
evenno = [2, 4, 6, 8, 10]
print("The first few even numbers are:", *evenno, "...")


The first few even numbers are: 2 4 6 8 10 ...


## Printing with labels

The notes show `cat()` with `fill=2` and labels generated from letters. fileciteturn2file0L144-L158

Python can reproduce the displayed idea with a loop.

In [8]:
import string

x = list(range(1, 11))

for letter, value in zip(string.ascii_lowercase[:10], x):
    print(f"( {letter} ): {value}")


( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10


# Lecture 37 – `paste()` and `paste0()`

R `paste()` concatenates strings and returns a new string/vector, unlike `cat()`, whose main purpose is output. It supports `sep` and `collapse`. fileciteturn2file0L174-L200

Python equivalents:
- `str.join()` – joining strings with a separator
- f-strings / string concatenation – combining individual values
- list comprehensions – vectorized string construction


In [9]:
# R: paste("Everybody", "loves", "R Programming.")
print(" ".join(["Everybody", "loves", "R Programming."]))

# R: paste(..., sep="*")
print("*".join(["Everybody", "loves", "R Programming."]))

# R: paste(..., sep="===")
print("===".join(["Everybody", "loves", "R Programming."]))


Everybody loves R Programming.
Everybody*loves*R Programming.
Everybody===loves===R Programming.


## Vectorized `paste()` example

In [10]:
names = ["Prof. Singh", "Mr. Venkat", "Dr. Jha"]

result = [f"{name} is a good person." for name in names]
result


['Prof. Singh is a good person.',
 'Mr. Venkat is a good person.',
 'Dr. Jha is a good person.']

## `collapse` equivalent

R's `collapse` combines the generated vector into one string. fileciteturn2file0L257-L267

In [11]:
collapsed = ", and ".join(result)
print(collapsed)


Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person.


## `paste()` with numbers and custom separator

In [12]:
parts = [1, " is first", 2, " is second", 3, " is third"]
print("#".join(map(str, parts)))

parts_with_spaces = [1, " is first ", 2, " is second ", 3, " is third "]
print("#".join(map(str, parts_with_spaces)))


1# is first#2# is second#3# is third
1# is first #2# is second #3# is third 


## Creating `Ex_1`, `Ex_2`, ...

In [13]:
x = [f"Ex_{i}" for i in range(1, 6)]
print(x)

print(x[0])  # R x[1]
print(x[1])  # R x[2]
print(x[2])  # R x[3]
print(x[4])  # R x[5]


['Ex_1', 'Ex_2', 'Ex_3', 'Ex_4', 'Ex_5']
Ex_1
Ex_2
Ex_3
Ex_5


### `collapse=""` equivalent

With R `paste("Ex", 1:5, sep="_", collapse="")`, the vector becomes one string. fileciteturn2file0L303-L323

In [14]:
x_vector = [f"Ex_{i}" for i in range(1, 6)]
x_single = "".join(x_vector)

print("Vector:", x_vector)
print("Single string:", x_single)


Vector: ['Ex_1', 'Ex_2', 'Ex_3', 'Ex_4', 'Ex_5']
Single string: Ex_1Ex_2Ex_3Ex_4Ex_5


## `paste0()` equivalent

The notes show that `paste0()` performs concatenation without the default space and supports vectorized combinations. fileciteturn2file0L328-L348

In [15]:
# R paste0(1:10)
print([str(i) for i in range(1, 11)])

# R paste0(1:10, c("st","nd","rd",rep("th",7)))
suffixes = ["st", "nd", "rd"] + ["th"] * 7
ordinals = [f"{i}{suffix}" for i, suffix in zip(range(1, 11), suffixes)]
print(ordinals)

# R paste(1:10, ...)
ordinals_with_space = [f"{i} {suffix}" for i, suffix in zip(range(1, 11), suffixes)]
print(ordinals_with_space)


['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
['1 st', '2 nd', '3 rd', '4 th', '5 th', '6 th', '7 th', '8 th', '9 th', '10 th']


# Lecture 38 – String Splitting

R `strsplit(x, split, fixed=FALSE)` splits character-vector elements using a delimiter or regular expression. fileciteturn2file0L361-L370

Python equivalents:
- `str.split()` for ordinary separators
- `re.split()` when regular expressions are needed


In [16]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

print("Split on '!':")
print(x.split("!"))

print("\nSplit on '&!':")
print(x.split("&!"))

print("\nSplit on '!&':")
print(x.split("!&"))


Split on '!':
['The&', 'syntax&', 'of&', 'paste&', 'is', '&available', ' &inthe online-help']

Split on '&!':
['The', 'syntax', 'of', 'paste', 'is!&available! &inthe online-help']

Split on '!&':
['The&!syntax&!of&!paste&!is', 'available! &inthe online-help']


## Accessing individual split components

In [17]:
y = x.split("!&")

print("Python first component:", y[0])
print("Python second component:", y[1])

# R y[[1]][3] would be NA for this example.
# Python raises IndexError if the element does not exist.
print("Number of components:", len(y))


Python first component: The&!syntax&!of&!paste&!is
Python second component: available! &inthe online-help
Number of components: 2


## Splitting dates

The notes split dates such as `2020-07-24` into year, month and day. fileciteturn2file0L443-L456

In [18]:
dates = ["2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27"]

dates_split = [date.split("-") for date in dates]

for row in dates_split:
    print(row)


['2020', '07', '24']
['2021', '08', '25']
['2022', '09', '26']
['2023', '10', '27']


## Convert split dates to a character matrix

The R notes use `unlist()` and `matrix()` to create a 4×3 character matrix. fileciteturn2file0L460-L469

In [19]:
date_matrix_text = np.array(dates_split, dtype=str)
print(date_matrix_text)
print("Shape:", date_matrix_text.shape)


[['2020' '07' '24']
 ['2021' '08' '25']
 ['2022' '09' '26']
 ['2023' '10' '27']]
Shape: (4, 3)


## Convert split dates to a numeric matrix

The notes also convert the split values to numbers before creating the matrix. fileciteturn2file0L474-L484

In [20]:
date_matrix_numeric = np.array(dates_split, dtype=int)
print(date_matrix_numeric)
print("Data type:", date_matrix_numeric.dtype)


[[2020    7   24]
 [2021    8   25]
 [2022    9   26]
 [2023   10   27]]
Data type: int64


## Split a word into individual characters

In [21]:
word = "Shalabh"
characters = list(word)
print(characters)


['S', 'h', 'a', 'l', 'a', 'b', 'h']


# Lecture 39 – String Manipulations and Alphabets

The notes introduce `nchar()` for counting characters and `nzchar()` for testing whether strings are non-empty. fileciteturn2file0L512-L530

In [22]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

print("Length of x:", len(x))
print("Length of y:", len(y))


Length of x: 19
Length of y: 26


## `nzchar()` equivalent

In [23]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

print(bool(x))
print(bool(y))

values = ["Apple", "Banana", "Cake"]
print([bool(v) for v in values])

values2 = ["Apple", "", "Cake"]
print([bool(v) for v in values2])


True
True
[True, True, True]
[True, False, True]


## Character counts for vectors and numbers

The notes show `nchar()` applied to character vectors and numeric values after conversion to character strings. fileciteturn2file0L579-L591

In [24]:
x = ["Apple", "Banana", "Cake"]
print([len(s) for s in x])

y = [2, 4, 6]
print([len(str(v)) for v in y])

z = [11, 222, 3333]
print([len(str(v)) for v in z])

z1 = [1.1, 2.22, 3.333]
print([len(str(v)) for v in z1])


[5, 6, 4]
[1, 1, 1]
[2, 3, 4]
[3, 4, 5]


## Lowercase and uppercase conversion

R's `tolower()` and `toupper()` convert alphabetic characters while leaving non-alphabetic characters unchanged. fileciteturn2file0L595-L610

Python equivalents are `.lower()` and `.upper()`.

In [25]:
x = "R course will start from 24.07.2022"
print(x.upper())

z = "INDIAN INSTITUTE OF TECHNOLOGY"
print(z.lower())


R COURSE WILL START FROM 24.07.2022
indian institute of technology


# Additional practice exercises

Run these cells to practice the same Week 9 concepts.

In [26]:
# Exercise 1: Create a sentence from separate words
words = ["Python", "is", "useful", "for", "data", "analysis"]
sentence = " ".join(words)
print(sentence)

# Exercise 2: Create IDs
ids = [f"Student_{i}" for i in range(1, 6)]
print(ids)

# Exercise 3: Split a CSV-style string
csv_text = "Apple,Banana,Cake,Donut"
print(csv_text.split(","))

# Exercise 4: Count characters
items = ["Data", "Science", "Python", "NPTEL"]
print({item: len(item) for item in items})

# Exercise 5: Change case
text = "Foundations of R Software"
print("Upper:", text.upper())
print("Lower:", text.lower())


Python is useful for data analysis
['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5']
['Apple', 'Banana', 'Cake', 'Donut']
{'Data': 4, 'Science': 7, 'Python': 6, 'NPTEL': 5}
Upper: FOUNDATIONS OF R SOFTWARE
Lower: foundations of r software


# R → Python Quick Reference

| R function/concept | Python equivalent |
|---|---|
| `print()` | `print()` |
| `cat()` | `print()`, `str.join()` |
| `paste()` | `"sep".join(...)`, f-strings |
| `paste0()` | `"" .join(...)`, f-strings |
| `collapse` | `str.join()` |
| `strsplit()` | `str.split()` / `re.split()` |
| `nchar()` | `len()` / `len(str(x))` |
| `nzchar()` | `bool()` for non-empty strings |
| `tolower()` | `.lower()` |
| `toupper()` | `.upper()` |

## Source coverage

The notebook follows the Week 9 PDF's four lectures:
- Lecture 36: `cat()` and string display
- Lecture 37: `paste()` / `paste0()`
- Lecture 38: `strsplit()` and date-matrix examples
- Lecture 39: `nchar()`, `nzchar()`, case conversion


# End of Week 9 Notebook

**Tip:** In Google Colab, use **Runtime → Run all** to execute every example from top to bottom.